### ISSUE TITLE
Scheduled background update checks crashes

### ISSUE THREAD

**Issue by Rool-IO** [hemker/apkgrabber#34]
Scheduled background update checks always crash the app :

FATAL EXCEPTION: main
Process: de.apkgrabber, PID: 6747
java.lang.RuntimeException: Unable to start receiver de.apkgrabber.receiver.AlarmReceiver_: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=de.apkgrabber/.service.UpdaterService_ (has extras) }: app is in background uid UidRecord{72f8a80 u0a403 RCVR idle change:idle|uncached procs:1 seq(0,0,0)}
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
	at android.app.ActivityThread.-wrap17(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=de.apkgrabber/.service.UpdaterService_ (has extras) }: app is in background uid UidRecord{72f8a80 u0a403 RCVR idle change:idle|uncached procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
	at android.app.ContextImpl.startService(ContextImpl.java:1477)
	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
	at org.androidannotations.api.builder.ServiceIntentBuilder.start(ServiceIntentBuilder.java:33)
	at de.apkgrabber.receiver.AlarmReceiver.onReceive(AlarmReceiver.java:27)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
	... 8 more

Also, if say it is scheduled for noon, it usually won't even start before quarter to one.

**Comment by hemker** [comment]
@Rool-IO should be fixed in new release. Please confirm, as my tests are only with an emulator and my Z3 Compact running Android 7.

**Comment by Rool-IO** [comment]
@hemker Can't actually tell as of now given the scheduled background checks (set to noon on both devices I use APKGrabber on - Oreo 8.1 & Pie) didn't occur with v1.4.

**Comment by Rool-IO** [comment]
Currently using it on Q beta 3, same behavior all around (other reported issues included).
Scheduled background checks still don't run with v1.4.

**Comment by hemker** [comment]
@Rool-IO The background updater problem should be fixed in current release, could you please confirm?

**Comment by hemker** [comment]
Other users confirmed this bug to be fixed. I close this one.

**Comment by Rool-IO** [comment]
Sorry I didn't see your question. It is fixed indeed on my end too. Thanks a lot
